### PR TITLE
Typography toast navigation card

### PR DESCRIPTION
**Pull request by samyakshah3008**
FEAT: 4 new components are now integrated in TripleS Library 
Note: Please avoid white space and commented lines, will refactor it later on 
Note: Updated sidebar according to new components added in all the html pages now 

Check out the live link: https://quirky-jang-ac862c.netlify.app/

### CODE REVIEW

**Review by PeeyushPrashant — APPROVED** [review]
Looks good, just try raising PR for each component separately, as it will be easy for the reviewer to go through the code.

**Review by vinc3nati — APPROVED** [review]
Suggestion: remove all the empty spaces in the CSS file, it's making it hard to go through.

**Review by SJTGSHIVAM — APPROVED** [review]
Looks good to merge

**Review by varnita619 — APPROVED** [review]
Looks good to go

**Pull request merged**
